projects:
  Kraiz_Preprod:
    schemaPath: graphql/schema.json
    includes:
      - Kraiz/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: tugm7vxnejcrbcil3afkhhxpdi
        codeGenTarget: swift
        generatedFileName: AppSyncObjects.swift
        docsFilePath: graphql
        region: us-west-2
      endpoints:
        prod: >-
          https://nv3vjybfpjdtxktpf5jvibilhm.appsync-api.us-west-2.amazonaws.com/graphql
